In [1]:
## Imports

import numpy as np
from scipy.linalg import eigh_tridiagonal

In [ ]:
## Either you can define your matrix (define as A) or make a random one


In [19]:
#Random matrix generation; don't run this cell if making your own


dim = 8
A_random = np.array([np.random.rand() for i in range(64)]).reshape(dim,dim)
A = (A_random + A_random.T)/2 #Symmetrise A

In [20]:
#For comparison with truncated eigenvalues
#Don't run this cell if you don't want to compare and just want the truncated eigenvalues

evals, evecs = np.linalg.eig(A)
evals = evals[evals.argsort()[::-1]]
evecs = evecs[:,evals.argsort()[::-1]] 

In [21]:
#Lanczos Scheme


#function definitions
def x_jfunc(A,v_j,b_j,v_jprev):
    return np.dot(A,v_j) - b_j*v_jprev

def alp_jfunc(x_j,v_j):
    return np.dot(x_j,v_j)

def w_jfunc(x_j,alp_j,v_j):
    return x_j - alp_j*v_j

def b_jnextfunc(w_j):
    return np.linalg.norm(w_j)

def v_jnextfunc(w_j,b_jnext):
    return (1/b_jnext)*w_j



## Initial conditions

v_1unnormalised = np.array([np.random.rand() for i in range(A.shape[0])])
v_1 = v_1unnormalised/np.linalg.norm(v_1unnormalised)
v_0 = np.array([0]*A.shape[0])
b_1 = 0


## Initial lists

vlist = [v_0,v_1]
blist = [0,b_1]
alist = [0]
xlist = [0]
wlist = [0]


#Generate all the relevant lists with a for loop
for i in range(A.shape[0]):    
    
    v_j = vlist[-1]
    b_j = blist[-1]
    v_jprev = vlist[-2]
    
    
    
    
    x_j = x_jfunc(A,v_j,b_j,v_jprev)
    xlist.append(x_j)
    
    a_j = alp_jfunc(x_j,v_j)
    alist.append(a_j)
    
    w_j = w_jfunc(x_j,a_j,v_j)
    wlist.append(w_j)
    
    b_jnext = b_jnextfunc(w_j)
    blist.append(b_jnext)
    
    v_jnext = w_j/b_jnext
    vlist.append(v_jnext)
    

    


In [22]:
def Tn_generator(alist, blist,n):
    
    ## Returns the truncated tridiagonalised matrix, which is easy to
    ## diagonalise and will have eigenvalues close to A
    
    ## not relevant if you just want the eigenvalues
    
    diag_array = alist[1:n+1]
    Tn = np.diag(diag_array)
    
    offdiag_array = blist[2:n+1]
    
    for i in range(n-1):
        Tn[i,i+1] = offdiag_array[i]
        Tn[i+1,i] = offdiag_array[i]
    
    
    
    return Tn

In [25]:
#Generate the eigenvalues for the nth truncated matrix (n<N)

def eigensolve(n):
    diag_array = alist[1:n+1]
    offdiag_array = blist[2:n+1]
    
    evals, evecs = eigh_tridiagonal(diag_array,offdiag_array)
    
    idx = evals.argsort()[::-1]
    
    evals = evals[idx]
    evecs = evecs[:,idx]
    
    return evals

In [26]:
np.round(eigensolve(8),4) == np.round(evals,4)

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [27]:
evals

array([ 3.95986125,  0.71977384,  0.52521887,  0.26678078, -0.11501493,
       -0.30501568, -0.60618781, -0.87940034])

In [28]:
eigensolve(8)

array([ 3.95986125,  0.71977384,  0.52521887,  0.26678078, -0.11501493,
       -0.30501568, -0.60618781, -0.87940034])

In [29]:
eigensolve(7)

array([ 3.95986125,  0.71444033,  0.44040399,  0.11751439, -0.26890257,
       -0.57396834, -0.87595138])

In [30]:
eigensolve(6)

array([ 3.95986125,  0.70328858,  0.33448057, -0.20545216, -0.4664136 ,
       -0.85823988])

In [31]:
eigensolve(5)

array([ 3.95986123,  0.6741041 ,  0.17107337, -0.31196847, -0.809619  ])

In [32]:
eigensolve(4)

array([ 3.95985916,  0.59383998, -0.2017832 , -0.6816505 ])

In [33]:
eigensolve(3)

array([ 3.95968226,  0.36564521, -0.40556967])

In [34]:
eigensolve(2)

array([ 3.94854658, -0.17961156])

In [35]:
eigensolve(1)

array([2.89963131])